### ISSUE TITLE
Nice work! May I ask some questions?

### ISSUE THREAD

**Issue by wjling** [lucdion/FlexLayout#16]
I read about YogaKit and your FlexLayout recently and I found that there is rarely a detail example or a guide to use it in normal development. I'm interesting in Yoga and FlexLayout and I consider two questions if I choose to import it in my project:
1. How does YogaKit or FlexLayout calculate cell heights in tableview or collectionview?
2. How to use YogaKit or FlexLayout to do animations?

**Comment by lucdion** [comment]
Hi @wjling,

Thanks, I totally agree that I should add more examples. I've some in the Example app, but it doesn't show all types of situations. You can have a look at example source code here: https://github.com/lucdion/FlexLayout/tree/master/Example/FlexLayoutSample/UI/Examples

1. Here you have two options:
* **intrinsicContentSize**: This source code is an example of using FlexLayout in a UITableView and UICollectionView cell. https://github.com/lucdion/LayoutFrameworkBenchmark/blob/master/LayoutFrameworkBenchmark/Benchmarks/FlexLayout/FeedItemFlexLayoutView.swift. The cell's class implement the intrinsicContentSize property. This works on a UITableView that use **UITableViewAutomaticDimension**.

* The other option is to implement **UITableViewDelegate** `func tableView(_ tableView: UITableView, **heightForRowAt** indexPath: IndexPath)` and returns the cell' height. You're cell must implement the `sizeThatFits()` method, see also the example which also implement sizeThatFits (https://github.com/lucdion/LayoutFrameworkBenchmark/blob/master/LayoutFrameworkBenchmark/Benchmarks/FlexLayout/FeedItemFlexLayoutView.swift)

func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
   // configure a temporary cell
   myTemplateCell.configure(....)
   return myTemplateCell.sizeThatFits(CGSize(width: myTableview.frame.width, height: .max)).height
}

2. Animation is not that difficult, you need to update flex items you want to animate and relayout its root flex container inside a UIView.animate() block. I will add an example soon.

```
UIView.animate(withDuration: 0.5, animations: {
        // Change the width of one flex item
        self.myViewToAnimate.flex.width(100)
        // relayout the flex container
        self.relayoutFlexboxContainer()
})

override func layoutSubviews() {
        super.layoutSubviews()
        rootFlexContainer.pin.top().left().width(100%).marginTop(topLayoutGuide)
        relayoutFlexboxContainer() 
}
    
fileprivate func relayoutFlexboxContainer() {
     rootFlexContainer.flex.layout()
 }
```

For animations I prefer the other project called PinLayout (https://github.com/mirego/PinLayout), which gives you more freedom over layouting. In some situations I use PinLayout, and on others I use FlexLayout. 

Thanks for your questions and comments!

**Comment by wjling** [comment]
Thank you for your nice reponse! I will try to learn more about the amazing layout

**Comment by lucdion** [comment]
@wjling I've added an example of a UITableView with variable height cells: https://github.com/lucdion/FlexLayout/blob/master/docs_markdown/examples.md

**Comment by wjling** [comment]
I have a try with Yoga and FlexLayout. I found the layout wired with some custom views nested in the cell. Everytime I scroll the collectionView, the cell's layout is different. Same layout, different appearances. So sad. T_T
![img_0169](https://user-images.githubusercontent.com/4201777/30028399-79f47e0e-91b7-11e7-819b-8ad4577dc664.PNG)
![img_0168](https://user-images.githubusercontent.com/4201777/30028403-7d6e3b56-91b7-11e7-9626-29f64790c024.PNG)
![img_0167](https://user-images.githubusercontent.com/4201777/30028408-805e2466-91b7-11e7-89d8-8e134e4730a8.PNG)

**Comment by wjling** [comment]
I found that pod 'FlexLayout' and its version is 0.8.1.  Maybe it should update ^_^. I just wonder why I could not find some functions, such as "markDirty" function,  in FlexLayout.swift. I have a lower version... I will manually import  the lastest source files into my project first and try again

**Comment by wjling** [comment]
Could I set a space when I use spaceBetween ?

**Comment by lucdion** [comment]
Hi @wjling, top update FlexLayout, you need to update the pod using `pod update`.

`. spaceBetween` will distributes items evenly in the main-axis; first item is at the beginning, last item at the end. To add more spacing around some items, you can set their margins:

```
rootFlexContainer.flex.justifyContent(.spaceBetween).define { (flex) in
            flex.addItem(aView).size(20).marginTop(5)
            flex.addItem(bView).size(20)
            flex.addItem(cView).size(20)
            flex.addItem(dView).size(20).marginBottom(5)
        }
```

**Comment by wjling** [comment]
OK. I take some tests and find every custom view should use a view as container to layout other subviews instead of just add subviews directly to the custom view. In this way I solve the wired layout above that caused by nested custom views. FlexLayout is quite good. One more question: the hidden views seem to be still in layout system, maybe the visible ones should be and the invisible should not ?

**Comment by lucdion** [comment]
Yes, you need to use `isIncludedInLayout` for that type of situations. You have to set isHidden and isIncludedInLayout separatly, this can be useful where you want to hide the view but keep its space on the layout.

I may add in the future a method that does both actions.
