### ISSUE TITLE
Horizontal Scroll View

### ISSUE THREAD

**Issue by KaKuiTsang** [lucdion/FlexLayout#21]
Hi, Everyone. I tried to make a horizontal scroll view by using overflow. 
I have a scrollview with a contentView inside. The contentView is set to have direction as .row, justifyContent as .spaceAround and wrap as .noWrap. Then I insert views into the contentView with width equal to the screen width and shrink equal to 0, hoping that the total width of the views I inserted can set the width of the contentView which then set the contentSize of the scrollview. However, it fails and instead I have to explicitly set the scrollView contentSize in order to make to scroll view scrolls. So my question is : Is there a way to make a horizontal scroll view without setting scrollView.contentSize explicitly using flexbox layout.
Thank you 😃

**Comment by lucdion** [comment]
Hi @KaKuiTsang, no, you need to set the scrollview contentSize once your flex container has been layouted.

Layout should be done in your ViewController viewDidLayoutSubviews method, and adjust the scrollview content size right after the flexbox root container has been layouted. 
 
``` 
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        view.flex.layout()
        scrollView.contentSize = contentView.frame.size
    }
```

That should do the work.

**Comment by KaKuiTsang** [comment]
@lucdion Got it! Thank you! 😄

**Comment by egenvall** [comment]
@KaKuiTsang  Mind sharing the code for your horizontal scrollview layout? I tried replicating it from your text, but with no success.
