### ISSUE TITLE
Help with some issues

### ISSUE THREAD

**Issue by patchthecode** [lucdion/FlexLayout#29]
Maybe we can use this as an example app to help others?
Not sure if i'm the only one stuck.

Here is my example app -> https://github.com/patchthecode/FlexLayoutPlayground
Just clone and do `pod update` and it should work.

I needed help on the following. I am not sure if i am not updating the layouts properly.

1. When i launch the app all seems well except for the bottom right blue `KiloMeters` label. I just dont know how to get it properly right aligned. Also it's width should take higher priority than the Label to the left of it. Blue view should fit the width of the label. And greenview to the left should take up the remaining space, but shrink if blueView needs more space. Left greenView number or lines of label is 2. If it cant fit, it should wrap to 2nd line.

<img width="295" alt="screen shot 2017-10-19 at 7 41 44 am" src="https://user-images.githubusercontent.com/2439146/31777222-6ab87018-b4a2-11e7-804a-2fe7849bc8ea.png">

2. As i start scrolling i sometimes (but not always) see the right padding disappear. When i checked it out, i realized that the green container view didnt adjust its width to fit the label.
<img width="293" alt="screen shot 2017-10-19 at 7 40 46 am" src="https://user-images.githubusercontent.com/2439146/31777549-24b2f6dc-b4a3-11e7-82c8-b4a64d2ae2b4.png">

3. The bottom right blue view starts sticking to the top. Also, theCompany name does not break to another line.

<img width="292" alt="screen shot 2017-10-19 at 7 41 23 am" src="https://user-images.githubusercontent.com/2439146/31777675-7a423eaa-b4a3-11e7-81d8-2db7dfea392c.png">

<img width="296" alt="screen shot 2017-10-19 at 7 41 02 am" src="https://user-images.githubusercontent.com/2439146/31777666-72f8ee3c-b4a3-11e7-8831-847bace104e2.png">

4. Also, with the number of lines on a label set to 0, I get this when i scroll.
<img width="290" alt="screen shot 2017-10-19 at 8 16 12 am" src="https://user-images.githubusercontent.com/2439146/31778553-cd4737a2-b4a5-11e7-8c49-87b8454af5c1.png">

Maybe it should get the width of the label first, and then wrap it if it cant fit? (or maybe i am just doing something wrong again 😅.

5. Lastly how do I make the cells height automatic?
i tried using `UICollectionViewFlowLayoutAutomaticSize` with an estimated height, but the views become wrong sizes. And nothing displays.

I'm pretty sure it must be something wrong im doing, so maybe If you help with this project, it can be used as an example for this repo? (if you want to of coruse)

Thanks!

**Comment by patchthecode** [comment]
I will also use this repository to try and find any other things that doesnt work when I try it. Hope it helps. I need develop a quick prototype by Monday, so unfortunately I may have to use pure-Layout temporarily until I can figure this out.

**Comment by lucdion** [comment]
Hi @patchthecode, I've fixed your major issue in this PR https://github.com/patchthecode/FlexLayoutPlayground/pull/1

The problem was how cell's height is computed.
