### ISSUE TITLE
Error add Carthage

### ISSUE THREAD

**Issue by sLm-s** [lucdion/FlexLayout#30]
Hello. Could not check before. Found an error

/Carthage/Build/iOS/YogaKit.framework/Headers/YGLayout.h:21:13: error: 'yoga/YGEnums.h' file not found #import <yoga/YGEnums.h>

 #import <yoga/YGEnums.h> 'yoga/YGEnums.h' file not found

**Comment by lucdion** [comment]
Hi @sLm-s, are you sure you are using the latest release of FlexLayout. Just to be sure execute `rm -rf Carthage/` and then update your carthage with `carthage update --use-ssh --platform iOS`.

Also, what is your version of Xcode?

**Comment by sLm-s** [comment]
I did not add  USE_YOGAKIT_PACKAGE preprocessor Macros. Therefore, an error.
I thought I should do this New Run Script 
Phase /usr/local/bin/carthage copy-frameworks
$(SRCROOT)/Carthage/Build/iOS/FlexLayout.framework
$(SRCROOT)/Carthage/Build/iOS/YogaKit.framework

**Comment by lucdion** [comment]
You're right! I've updated the Carthage documentation section, see https://github.com/lucdion/FlexLayout#carthage

**Comment by sLm-s** [comment]
OK thank you very much. Very good framework

**Comment by lucdion** [comment]
Thanks @sLm-s
