### ISSUE TITLE
Recalculate FlexConteiner

### ISSUE THREAD

**Issue by sLm-s** [lucdion/FlexLayout#31]
How to recalculate the entire container if one object is hidden and the container is compressed ?

**Comment by lucdion** [comment]
@sLm-s you must call `isincludedinlayout(false)` (https://github.com/lucdion/FlexLayout#isincludedinlayout) on your hidden object. Then you need to relayout the flex container, e.g: `container.flex.layout(mode: .adjustHeight)`

**Comment by lucdion** [comment]
You must keep a reference on the container (UIView).
```
    hiddenableView = UIView()
    flex_1.addItem(hiddenableView).direction(.column).padding(16).grow(1).shrink(1).define({ (flex_2) in
              flex_2.addItem(nameLabel)
              flex_2.addItem(priceLabel).marginTop(8)
              flex_2.addItem(priceDiscount).marginTop(8)
              flex_2.addItem(priceSaving).marginTop(8)
             flex_2.addItem(maximumOrder).marginTop(8)
         })
...

hiddenableView.isHidden = true
hiddenableView.isIncludedInLayout(false)
rootFlexContainer.flex.layout(mode: .adjustHeight)
```

**Comment by sLm-s** [comment]
Thank you, you helped me out.
