### ISSUE TITLE
Question marginBottom() 

### ISSUE THREAD

**Issue by sLm-s** [lucdion/FlexLayout#32]
Hi @lucdion. When we hide the object with selec.flex.isIncludedInLayout (false), it disappears, but its marginBottom (8) remains, and afterwards there is a large blank if there are many such objects. How to hide an object completely with all its indents ?

**Comment by lucdion** [comment]
Hi @sLm-s, can you share me the source code section?

**Comment by sLm-s** [comment]
If there is text then show.

```
self.priceLabel.flex.isIncludedInLayout(true)
self.priceDiscount.flex.isIncludedInLayout(true)
self.priceSaving.flex.isIncludedInLayout(true)
self.maximumOrder.flex.isIncludedInLayout(true)
                    
self.priceLabel.flex.markDirty()
self.priceDiscount.flex.markDirty()
self.priceSaving.flex.markDirty()
self.maximumOrder.flex.markDirty()
contentView.flex.layout(mode: .adjustHeight)
```

If there is nothing hidden

```
priceLabel.flex.isIncludedInLayout(false)
priceDiscount.flex.isIncludedInLayout(false)
priceSaving.flex.isIncludedInLayout(false)
maximumOrder.flex.isIncludedInLayout(false)

priceLabel.flex.markDirty()
priceDiscount.flex.markDirty()
priceSaving.flex.markDirty()
maximumOrder.flex.markDirty()
contentView.flex.layout(mode: .adjustHeight)
```

And the layout

```
contentView.flex.direction(.column).paddingTop(20).define { (flex) in
            
            flex.addItem(cvImage).height(370).marginBottom(8)
            
            flex.addItem().direction(.column).padding(16).grow(1).define({ (flex) in
                flex.addItem(nameLabel).grow(1)
                
                flex.addItem(priceLabel).grow(1).marginTop(8)
                flex.addItem(priceDiscount).grow(1).marginTop(8)
                flex.addItem(priceSaving).grow(1).marginTop(8)
                flex.addItem(maximumOrder).grow(1).marginTop(8)
                
                
                flex.addItem(selectExtra).marginTop(8).marginBottom(8)
                
                flex.addItem(conteinerAva).direction(.row).marginTop(8).define({ (flex) in
                    flex.addItem(iconAvailable)
                    flex.addItem(availableLabel).marginLeft(8).grow(1)
                })
                
                flex.addItem(deliveryDay).marginTop(8).grow(1)
                flex.addItem(noProduct).marginTop(8).grow(1)
                
                flex.addItem().alignItems(.start).marginTop(8).define({ (flex) in
                    flex.addItem(buttonFromBook)
                    flex.addItem(buttonAdd).marginTop(8)
                })

            })
  
        }

```

These objects are mostly hidden

flex.addItem(priceLabel).grow(1).marginTop(8)
flex.addItem(priceDiscount).grow(1).marginTop(8)
flex.addItem(priceSaving).grow(1).marginTop(8)
flex.addItem(maximumOrder).grow(1).marginTop(8)

This is a CollectionView in which the height changes if there is more than fill and nach zero                

flex.addItem(selectExtra).marginTop(8).marginBottom(8)

The objects themselves disappear, but their indents remain.

**Comment by lucdion** [comment]
If I understand correctly, the issue is with `selectExtra`, its the one with `marginBottom(8)`?
Have you tried to call `selectExtra.flex.markDirty()`?

**Comment by sLm-s** [comment]
![simulator screen shot - iphone 8 - 2017-11-01 at 20 55 03](https://user-images.githubusercontent.com/20534572/32280959-9c4a2ea0-bf47-11e7-84b1-cf5451a650a3.png)

And another question. Tell me how to make such a layout from two UILabel ?

**Comment by sLm-s** [comment]
All the margins of these objects do not hide

flex.addItem(priceLabel).grow(1).marginTop(8)
flex.addItem(priceDiscount).grow(1).marginTop(8)
flex.addItem(priceSaving).grow(1).marginTop(8)
flex.addItem(maximumOrder).grow(1).marginTop(8)

flex.addItem(selectExtra).marginTop(8).marginBottom(8)

**Comment by sLm-s** [comment]
I beg forgiveness but I think you're right. The problem is basically the flex.addItem(selectExtra).marginTop(8).marginBottom(8). Both indents remain and the object is hidden. 

They both remain
marginTop(8) marginBottom(8)

**Comment by lucdion** [comment]
It is difficult to find your issue without a running example. For your other questions, this will do the trick:
```
       flex.addItem().direction(.row).paddingHorizontal(18).backgroundColor(.cyan).define({ (flex) in
                flex.addItem(redLabel).width(50%).marginVertical(10)
                flex.addItem(blueLabel).shrink(1).marginLeft(10)
       })
```

<img width="332" alt="screen shot 2017-11-01 at 11 36 37 am" src="https://user-images.githubusercontent.com/14981341/32282858-1fed33a0-bef9-11e7-85b8-02f34c7453dc.png">

**Comment by sLm-s** [comment]
Thank you so much.
Is there a version of why indenting does not disappear?  marginTop(8) marginBottom(8)

**Comment by sLm-s** [comment]
@lucdion I found the cause of my problem. Thanks a lot for your help.

**Comment by lucdion** [comment]
Hi @sLm-s, I'm really interested to know the reason of your issue.

**Comment by sLm-s** [comment]
(selectExtra) is a collection inside the cell to display certain data. The condition was established if any data came to the collection, then you calculate its height and show it. The problem was that initially there was nothing that was (nil) and the object was hiding and after the update came an empty array and the object appeared but with a zero size and therefore it seemed that the indents did not hide.

**Comment by lucdion** [comment]
Ok nice, it was an application specific issue. Thanks
